name: Release NodeJS

on:
  push:
    branches: [main]

env: 
  AUTH: ${{ secrets.AUTH }}
  OWNER: ${{ secrets.OWNER }}
  REPO: ${{ secrets.REPO }}

- name: Upload To Github Release
  uses: xresloader/upload-to-github-release@v1.3.4
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    delete_file: "**"
    delete_file: "dist/**"
    tags: true
    draft: true